name: Build and Publish .NET App with React Client

on:
  push:
    branches:
      - main # or your main branch
  pull_request:
    branches:
      - main # or your main branch

jobs:
  build:
    runs-on: self-hosted
    env:
      HOME: ${{ github.workspace }}
      
    steps:
      - name: Backup db
        run: |
          if test -f "${{ github.workspace }}/publish/mydb.db"; then
            mkdir -p /root/db_backups
            mv ${{ github.workspace }}/publish/mydb.db /root/db_backups
            cd /root/db_backups
            zip backup_${{ github.sha }}.zip mydb.db
          else
            echo "mydb.db not found, skipping backup."
          fi


      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          
      - name: Clean and install dependencies
        run: |
          cd basemicrosaasapp.client
          rm -rf node_modules package-lock.json
          npm install
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Replace appsettings.json
        run: |
          # Stop the build if the production appsettings file doesn't exist
          if [ ! -f /opt/cartrack/appsettings.Production.json ]; then
            echo "Error: Production appsettings.json not found at /opt/app/appsettings.Production.json"
            exit 1
          fi
          # Replace appsettings.json in the server project with the production version
          cp /opt/cartrack/appsettings.Production.json BaseMicroSaasApp.Server/appsettings.json
          # Verify the file was copied
          ls -l BaseMicroSaasApp.Server/appsettings.json

      - name: Stop service (restart and exit on failure)
        run: |
          if ! sudo systemctl stop cartrack-app.service; then
            echo "Failed to stop service, attempting restart..."
            sudo systemctl restart cartrack-app.service
            echo "Service restarted due to stop failure. Exiting workflow."
            exit 1
          fi

      - name: Publish
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish

      - name: Restore db
        run: |
          mkdir -p ${{ github.workspace }}/publish
          mv /root/db_backups/mydb.db ${{ github.workspace }}/publish/
          
      - name: Move React Build Output
        run: |
          rm -rf /var/www/cartrack/html
          mkdir -p /var/www/cartrack/html
          cp -r ${{ github.workspace}}/basemicrosaasapp.client/dist/* /var/www/cartrack/html

      - name: Reload/Restart cartrack.service
        run: |
          # Attempt to reload the service first (less disruptive)
          sudo systemctl restart cartrack-app.service
          if [ $? -ne 0 ]; then
            exit 1
          fi
