name: Build and Publish .NET App with React Client

on:
  push:
    branches:
      - main # or your main branch
  pull_request:
    branches:
      - main # or your main branch

jobs:
  build:
    runs-on: self-hosted
    env:
      HOME: ${{ github.workspace }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Publish
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish

      - name: Build React App
        run: |
          cd basemicrosaasapp.client
          npm install
          npm run build

      - name: Move React Build Output
        run: |
          rm -rf ${{ github.workspace }}/publish/wwwroot
          mkdir -p ${{ github.workspace }}/publish/wwwroot
          cp -r basemicrosaasapp.client/dist/* ${{ github.workspace }}/publish/wwwroot
